org: toguvr
app: express-similarity
service: express-similarity
frameworkVersion: '3'

plugins:
  - serverless-offline



provider:
  name: aws
  runtime: nodejs18.x
  apiGateway:
    binaryMediaTypes:
      - '*/*'

functions:
  api:
    handler: index.handler
    timeout: 10
    events:
      - httpApi: '*'
